config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cross_answers#index' 
  resources :students, only: [:index, :new, :create]
  resources :lessons, only: [:index, :new, :create]
  resources :cross_answers, only: [:index, :create, :update, :destroy]
  resources :members, only: [:new, :create]
  resources :battings do
    collection do
      get 'search'
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batting.rb
class Batting < ApplicationRecord
  has_many :members
end

app/models/cross_answer.rb
class CrossAnswer < ApplicationRecord
  belongs_to :lesson
  belongs_to :student
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :cross_answers
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :battings
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :cross_answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/battings_controller.rb
class BattingsController < ApplicationController
  def new
    @batting = Batting.new
  end

  def create
    @batting = Batting.new(battings_params)
    if @batting.valid?
      @batting.save
      redirect_to root_path
    else
      render new
    end
  end

  def search
    member = Member.find_by(uniform_number: params[:keyword])
    render json:{ member: member }
  end


  private
  def battings_params
    params.require(:batting).permit(:member_id, :batting_number, :position_id)
  end
end

app/controllers/cross_answers_controller.rb
class CrossAnswersController < ApplicationController
  def index
    @lessons = Lesson.all
    @students = Student.all
    @cross_answers = CrossAnswer.all
    if params[:lesson_id] && params[:student_id]
      set_cross_answer
    else
    @cross_answer = CrossAnswer.new
    end

  end
  def create
    @cross_answer = CrossAnswer.new(cross_answer_params)
    if @cross_answer.save
      redirect_to root_path
    else
      render :index
    end
  end

  def update
    @cross_answer = CrossAnswer.find(params[:id])
    if @cross_answer.update(cross_answer_params)
      redirect_to cross_answers_path
    end
  end

  private
  def cross_answer_params
    params.require(:cross_answer).permit(:lesson_id, :student_id, :writing, :mark)
  end

  def set_cross_answer
    @cross_answer = CrossAnswer.find_by(lesson_id: params[:lesson_id], student_id: params[:student_id])
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
  end
  def new
    @lesson = Lesson.new
  end
  
  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def lesson_params
    params.require(:lesson).permit(:name)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
      @members = Member.new
  end

  def create
    @members = Member.new(member_params)
    if @members.valid?
      @members.save
      return redirect_to root_path
    else
      render :new
    end
  end

  private
  def member_params
    params.require(:member).permit(:uniform_number, :grade, :first_name,:last_name)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battings_helper.rb
module BattingsHelper
end

app/helpers/cross_answers_helper.rb
module CrossAnswersHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/battings/new.html.erb
<%= form_with(model: @batting, url: battings_path, local: true) do |form| %>
	
		<div class="orders">
			<table class="orders-new">
				<tr class="orders-new-registration">
					<th class="game-batting-order">打順</th>
					<th class="game-uniform-number">背番号</th>
					<th class="game-grade">学年</th>
					<th class="game-full-name">名前</th>
					<th class="game-defensive">守備</th>
				</tr>
			
					<tr class="orders-new-registration">
						<td class="input-form-1">
							<%= form.text_field :batting_number, class:"input-game-uniform-number" %>
						</td>
						<td class="input-form-2">
							<%= form.hidden_field :member_id, id:"member_id" %>
              <input type="text" class="kensaku" id="form" >
						</td>
						<td class="input-form-3">
							<input type="text" class="input-game-grade", id="grade_id"/>
						</td>
						<td class="input-form-4">
							<input type="text" class="input-game-full-name", id="full-name"/>
						</td>
						<td class="input-form-5">
							<%= form.text_field :position_id %>
						</td>
					</tr>
			</table>
		</div>
		<div class="btn">
			<%= form.submit "登録", class:"btn-games-index" %>
		</div>
	<% end %>
  <%= link_to 'TOPに戻る', root_path, class: 'btn-members-index' %>

app/views/cross_answers/index.html.erb
<%= link_to "科目登録", new_lesson_path %>
<%= link_to "生徒登録", new_student_path %>
<%= link_to "選手登録", new_member_path %>
<%= link_to "打順登録", new_batting_path %>

<div id="cross-matrix">
  <table class="matrix">
    <thead>
      <tr class="matrix">
        <td class="matrix"></td>
        <% @lessons.each do |lesson| %>
          <td class="matrix">
            <%= lesson.name %>
          </td>
        <% end %>
      </tr>
    <thead>
    <tbody>
      <% @students.each_with_index do |student, i| %>
        <tr class="matrix">
          <th class="matrix">
            <%= student.name %>
          </th>
          <% @lessons.each_with_index do |lesson, k| %>
            <td class="grade-info matrix">
              <div class="hidden lesson-num">
                <%= lesson.id%>
              </div>
              <div class="hidden student-num">
                <%= student.id %>
              </div>
              <% if @cross_answers.where(lesson_id: lesson.id, student_id: student.id).present? %>
                <% cross_answer = @cross_answers.find_by(lesson_id: lesson.id, student_id: student.id) %>
                <%= link_to cross_answers_path(lesson_id: cross_answer.lesson_id, student_id: cross_answer.student_id) do %>
                  <%= cross_answer.writing %>
                  <%= cross_answer.mark %>
                <% end %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% unless params[:lesson_id] && params[:student_id] %>
  <div id="mask" class="hidden">
    <section id="modal" class="hidden">
      <div id="close">
        閉じる
      </div>
      <%= form_with model: @cross_answer, local: true do |f| %>
        <%= f.text_field :lesson_id, class:"hidden",id:"lesson_id-input"%>
        <%= f.text_field :student_id, class:"hidden", id:"student_id-input" %>
        <div>
          <label>筆記点数</label> 
          <%= f.text_field :writing %>
        </div>
        <div>
          <label>マーク点数</label>
          <%= f.text_field :mark %>
        </div>
        <%= f.submit %>
      <% end %>
    </section>
  </div>
<% else %>
  <div id="edit-mask">
    <section id="modal">
      <%= link_to cross_answers_path do %>
        <div id="edit-close">
          閉じる
        </div>
      <% end %>
      <%= form_with model: @cross_answer, url:cross_answer_path(@cross_answer.id), local: true do |f| %>
        <%= f.hidden_field :id %>
        <%= f.text_field :lesson_id, class:"hidden",id:"lesson_id-input"%>
        <%= f.text_field :student_id, class:"hidden", id:"student_id-input" %>
        <div>
          <label>筆記点数</label> 
          <%= f.text_field :writing %>
        </div>
        <div>
          <label>マーク点数</label>
          <%= f.text_field :mark %>
        </div>
        <%= f.submit %>
      <% end %>
    </section>
  </div> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrossApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/new.html.erb
<div id="new-lesson">
  <%= form_with model: @lesson, local: true do |f| %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
</div>
<%= link_to "トップページ", root_path %>

app/views/members/new.html.erb
<%= form_with(model: @members, url: members_path, local: true) do |form| %>
  <div class="members">
    <table class="members-new">
      <tr class="members-new-tr-1">
        <th class="uniform-number">背番号</th>
        <th class="grade">学年</th>
        <th class="first-name">姓</th>
        <th class="last-name">名</th>
      </tr>
      <tr>
        <td class="uniform-number">
          <%= form.text_field :uniform_number, class:"input-uniform-number" %>
        </td>
        <td class="grade">
          <%= form.text_field :grade, class:"input-grade" %>
        </td>
        <td class="first-name">
          <%= form.text_field :first_name, class:"input-first-name" %>
        </td>
        <td class="last-name">
          <%= form.text_field :last_name, class:"input-last-name" %>
        </td>
      </tr>
    </table>
  </div>
  <div class="btn">
    <%= form.submit "登録", class:"members-btn" %>
    <%= link_to '一覧', members_path, class: 'btn-members-index' %>
  </div>
<% end %>
<%= link_to 'TOPに戻る', root_path, class: 'btn-members-index' %>

app/views/students/new.html.erb
<div id="new-student">
  <%= form_with model: @student, local: true do |f| %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
</div>
<%= link_to "トップページ", root_path %>